=== surelogic/jsure/lib/oldxml/promises.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT package (promise*, class*)>
<!ATTLIST package
	name 	CDATA	#REQUIRED
>

<!ELEMENT class (promise*, classinit?, (constructor | field | method | class)*)>
<!ATTLIST class
    name    CDATA    #REQUIRED
	
>

<!ELEMENT classinit (promise*)>

<!ELEMENT constructor (promise*, receiver?, parameter*)>
<!ATTLIST constructor
    params  CDATA    ""
>

<!ELEMENT field (promise*)>
<!ATTLIST field
    names   CDATA    #REQUIRED
>

<!ELEMENT method (promise*, receiver?, retval?, parameter*)>
<!ATTLIST method
	name    CDATA    #REQUIRED
	params  CDATA    ""
>

<!ELEMENT parameter (promise*)>
<!ATTLIST parameter
	index  CDATA    #REQUIRED
	type   CDATA    ""
>

<!ELEMENT receiver (promise*)>
<!ELEMENT retval (promise*)>

<!ELEMENT promise EMPTY>
<!ATTLIST promise
	keyword  CDATA    #REQUIRED
	contents CDATA    ""
>

=== surelogic/jsure/lib/oldxml/java.awt.image.promises.xml
<?xml version="1.0" encoding="UTF-8"?>
 
<!DOCTYPE package SYSTEM "promises.dtd">

<package name="java.awt.image">
  <promise keyword="promise"
      contents="&quot;colorImport java.awt.*;&quot; for *"/>

      <promise keyword="promise"
	contents="&quot;transparent&quot; for add*Listener(**) | remove*Listener(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for get*(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for add*(**) &amp; !(add*Listener(**))"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for new(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for process*(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for set*(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for updateUI()"/>
  <promise keyword="promise"
    contents="&quot;transparent&quot; for revalidate()"/>

  <promise keyword="promise"
    contents="&quot;transparent&quot; for repaint(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint AWT;&quot; for fire*(**)"/>


  <promise keyword="promise"
    contents="&quot;colorConstraint AWT;&quot; for requestFocus*(**)"/>


  <promise keyword="promise"
    contents="&quot;colorConstraint AWT;&quot; for paint*(**)"/>

  <promise keyword="promise"
    contents="&quot;reads Instance&quot; for getGraphics()"/>
  <promise keyword="promise"
    contents="&quot;writes java.awt.event.ActionListener.GUIinternal&quot; for getGraphics()"/>  

</package>

=== surelogic/jsure/lib/oldxml/java.awt.Button.promises.xml
<?xml version="1.0" encoding="UTF-8"?>
 
<!DOCTYPE package SYSTEM "promises.dtd">

<package name="java.awt">
    <class name="Button">
    <promise keyword="colorImport" contents="java.awt.*;"/>
    
    <promise keyword="mapRegion"
      contents="Instance into java.awt.event.ActionListener#GUIstuff"/>

    <promise keyword="promise"
	    contents="&quot;transparent&quot; for add*Listener(**) | remove*Listener(**)"/>
	  <promise keyword="promise"
	    contents="&quot;writes java.awt.event.ActionListener.GUIinternal&quot; for add*Listener(**) | remove*Listener(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for get*(**) | new(**)"/>
  <promise keyword="promise"
    contents="&quot;reads java.awt.event.ActionListener.GUIinternal&quot; for new(**)"/>
  <promise keyword="promise"
    contents="&quot;reads Instance&quot; for get*(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for add*(**) &amp; !(add*Listener(**))"/>
  <promise keyword="promise"
    contents="&quot;writes Instance&quot; for add*(**) &amp; !(add*Listener(**))"/>  

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for process*(**)"/>
  <promise keyword="promise"
    contents="&quot;reads java.awt.event.ActionListener.GUIinternal&quot; for process*(**)"/>  
  <promise keyword="promise"
    contents="&quot;writes Instance&quot; for process*(**)"/>  

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for set*(**)"/>
  <promise keyword="promise"
    contents="&quot;writes Instance&quot; for set*(**)"/>

    </class>  
</package>

=== surelogic/jsure/lib/oldxml/java.awt.Graphics2D.promises.xml
<?xml version="1.0" encoding="UTF-8"?>
 
<!DOCTYPE package SYSTEM "promises.dtd">

<package name="java.awt">
    <class name="Graphics2D">

    <promise keyword="colorImport" contents="java.awt.*;"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for get*(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for set*(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for draw*(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for fill*(**)"/>

  <promise keyword="promise"
    contents="&quot;colorConstraint GUI;&quot; for translate(**)"/>

    </class>
</package>
